name: MCP Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR diff
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr.diff

      - name: Get push diff
        if: github.event_name == 'push'
        run: |
          git diff ${{ github.event.before }} ${{ github.event.after }} > pr.diff

      - name: Start MCP Server
        run: |
          dotnet run --project /Users/ertanaktas/Desktop/DotnetApps/CodereviewMCP/reviewMCP/reviewMCP.csproj &
          sleep 5 # MCP server'ın başlaması için bekle

      - name: Run MCP Code Review
        id: review
        run: |
          review=$(cat pr.diff | dotnet run --project /Users/ertanaktas/Desktop/DotnetApps/CodereviewMCP/reviewMCP/reviewMCP.csproj tool ReviewCommit)
          echo "review=$review" >> $GITHUB_OUTPUT

      - name: Post review as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🛡️ **MCP Code Review:**\n\n${{ steps.review.outputs.review }}`
            }) 